"""tambah kolom detail pemeriksaan awal di appointment

Revision ID: 16bde7236cb5
Revises: 1f567ae994bf
Create Date: 2025-09-12 17:27:07.300005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16bde7236cb5'
down_revision = '1f567ae994bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tekanan_darah_sistol', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tekanan_darah_diastol', sa.Integer(), nullable=True))
        batch_op.alter_column('berat_badan',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('tekanan_darah')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tekanan_darah', sa.VARCHAR(length=10), nullable=True))
        batch_op.alter_column('berat_badan',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('tekanan_darah_diastol')
        batch_op.drop_column('tekanan_darah_sistol')

    # ### end Alembic commands ###
