"""Add checked_in status to Appointment

Revision ID: 1f567ae994bf
Revises: 3503a9c4e188
Create Date: 2025-09-06 19:21:03.678647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f567ae994bf'
down_revision = '3503a9c4e188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_in', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('checked_in')

    # ### end Alembic commands ###
